"""Abstract repository ports (interfaces) — no implementation details."""
from __future__ import annotations
from abc import ABC, abstractmethod
from uuid import UUID

from dupe_platform.domain.models import (
    Project, Unit, Client, PaymentPlan, Installment,
    BankTransaction, ReconciliationMatch, Budget, Notification,
)


class ProjectRepository(ABC):
    @abstractmethod
    async def get(self, project_id: UUID) -> Project | None: ...
    @abstractmethod
    async def list_all(self) -> list[Project]: ...
    @abstractmethod
    async def save(self, project: Project) -> None: ...
    @abstractmethod
    async def get_units(self, project_id: UUID) -> list[Unit]: ...
    @abstractmethod
    async def save_unit(self, unit: Unit) -> None: ...


class ClientRepository(ABC):
    @abstractmethod
    async def get(self, client_id: UUID) -> Client | None: ...
    @abstractmethod
    async def list_all(self) -> list[Client]: ...
    @abstractmethod
    async def save(self, client: Client) -> None: ...
    @abstractmethod
    async def find_by_id_number(self, id_number: str) -> Client | None: ...


class PaymentPlanRepository(ABC):
    @abstractmethod
    async def get(self, plan_id: UUID) -> PaymentPlan | None: ...
    @abstractmethod
    async def list_by_project(self, project_id: UUID) -> list[PaymentPlan]: ...
    @abstractmethod
    async def list_by_client(self, client_id: UUID) -> list[PaymentPlan]: ...
    @abstractmethod
    async def save(self, plan: PaymentPlan) -> None: ...
    @abstractmethod
    async def get_overdue_installments(self) -> list[Installment]: ...
    @abstractmethod
    async def get_installments_due_soon(self, days_ahead: int) -> list[Installment]: ...


class TransactionRepository(ABC):
    @abstractmethod
    async def get(self, tx_id: UUID) -> BankTransaction | None: ...
    @abstractmethod
    async def list_unmatched(self) -> list[BankTransaction]: ...
    @abstractmethod
    async def save_batch(self, transactions: list[BankTransaction]) -> None: ...
    @abstractmethod
    async def save_match(self, match: ReconciliationMatch) -> None: ...
    @abstractmethod
    async def get_matches(self, transaction_id: UUID) -> list[ReconciliationMatch]: ...


class BudgetRepository(ABC):
    @abstractmethod
    async def get_by_project(self, project_id: UUID) -> Budget | None: ...
    @abstractmethod
    async def save(self, budget: Budget) -> None: ...


class NotificationRepository(ABC):
    @abstractmethod
    async def save(self, notification: Notification) -> None: ...
    @abstractmethod
    async def already_sent(self, installment_id: UUID, trigger: str) -> bool: ...
    @abstractmethod
    async def list_by_client(self, client_id: UUID) -> list[Notification]: ...
